-- Update book descriptions to be more detailed and informative
-- This script updates all book descriptions in the database with more comprehensive information

USE perpustakaan;

-- Update descriptions for Fiction books
UPDATE books SET description = 'Sebuah novel klasik Amerika yang menggambarkan era Jazz Age di tahun 1920-an. Mengisahkan tentang Jay Gatsby, seorang jutawan misterius yang mencoba memenangkan kembali cinta masa lalunya, Daisy Buchanan. Novel ini mengeksplorasi tema-tema tentang impian Amerika, korupsi, dan ilusi versus kenyataan. Ditulis dengan gaya prosa yang indah dan simbolisme yang mendalam, The Great Gatsby dianggap sebagai salah satu karya sastra Amerika terbesar.' WHERE title = 'The Great Gatsby';

UPDATE books SET description = 'Sebuah novel yang menggambarkan ketidakadilan rasial dan kepolosan masa kanak-kanak di Amerika Selatan. Dikisahkan melalui sudut pandang Scout Finch, seorang gadis kecil yang menyaksikan ayahnya, Atticus Finch, membela seorang pria kulit hitam yang dituduh melakukan kejahatan. Novel ini mengeksplorasi tema-tema tentang rasisme, moralitas, dan kehilangan kepolosan. To Kill a Mockingbird adalah karya sastra yang powerful dan timeless yang terus relevan hingga hari ini.' WHERE title = 'To Kill a Mockingbird';

UPDATE books SET description = 'Sebuah novel distopia yang menggambarkan dunia di bawah kendali totaliter Big Brother. Mengisahkan tentang Winston Smith yang hidup di Oceania, sebuah negara super yang mengawasi setiap aspek kehidupan warganya. Novel ini mengeksplorasi tema-tema tentang pengawasan, kontrol pikiran, dan manipulasi kebenaran. 1984 adalah peringatan yang kuat tentang bahaya totalitarianisme dan pentingnya kebebasan berpikir.' WHERE title = '1984';

UPDATE books SET description = 'Sebuah novel romantis yang menggambarkan kehidupan Elizabeth Bennet dan Mr. Darcy di Inggris abad ke-19. Mengisahkan tentang prasangka, kesombongan, dan cinta sejati yang mengatasi segala rintangan sosial. Novel ini mengeksplorasi tema-tema tentang kelas sosial, pernikahan, dan peran wanita dalam masyarakat. Pride and Prejudice adalah salah satu karya sastra romantis paling terkenal dan dicintai sepanjang masa.' WHERE title = 'Pride and Prejudice';

UPDATE books SET description = 'Sebuah novel kontroversial tentang pemberontakan remaja yang mengisahkan tentang Holden Caulfield, seorang remaja yang dikeluarkan dari sekolah dan mengembara di New York City. Novel ini mengeksplorasi tema-tema tentang alienasi, kepolosan, dan pencarian identitas. The Catcher in the Rye adalah karya sastra yang powerful tentang perjalanan seorang remaja menuju kedewasaan.' WHERE title = 'The Catcher in the Rye';

-- Update descriptions for Fantasy books
UPDATE books SET description = 'Sebuah novel fantasi epik yang mengisahkan tentang Bilbo Baggins, seorang hobbit yang terlibat dalam petualangan yang tidak terduga. Bersama dengan sekelompok kurcaci dan penyihir Gandalf, Bilbo melakukan perjalanan ke Gunung Kesepian untuk merebut kembali harta karun dari naga Smaug. Novel ini penuh dengan makhluk fantasi, petualangan yang menegangkan, dan pesan tentang keberanian dan persahabatan. The Hobbit adalah prekuel dari The Lord of the Rings dan telah menjadi klasik sastra fantasi.' WHERE title = 'The Hobbit';

UPDATE books SET description = 'Buku pertama dalam seri Harry Potter yang mengisahkan tentang seorang anak laki-laki yatim piatu yang menemukan bahwa dia adalah seorang penyihir. Harry Potter diundang untuk belajar di Sekolah Sihir Hogwarts, di mana dia menemukan teman-teman sejati, menghadapi bahaya, dan mulai memahami warisan keluarganya. Novel ini penuh dengan sihir, petualangan, dan pesan tentang persahabatan, keberanian, dan kebaikan melawan kejahatan. Harry Potter and the Philosopher\'s Stone telah menjadi fenomena budaya global.' WHERE title = 'Harry Potter and the Philosopher\'s Stone';

UPDATE books SET description = 'Sebuah seri novel fantasi yang mengisahkan tentang petualangan sekelompok anak-anak di dunia magis Narnia. Melalui lemari ajaib, mereka memasuki dunia yang penuh dengan makhluk fantasi, sihir, dan petualangan epik. Novel ini mengeksplorasi tema-tema tentang kebaikan melawan kejahatan, pengorbanan, dan pertumbuhan spiritual. The Chronicles of Narnia adalah karya sastra fantasi yang telah menginspirasi generasi pembaca.' WHERE title = 'The Chronicles of Narnia';

-- Update descriptions for Mystery books
UPDATE books SET description = 'Sebuah novel thriller misteri yang mengisahkan tentang Robert Langdon, seorang profesor simbolisme yang terlibat dalam konspirasi besar. Ketika kurator museum Louvre ditemukan tewas, Langdon harus memecahkan teka-teki kuno yang mengarah pada rahasia yang telah tersembunyi selama berabad-abad. Novel ini penuh dengan teka-teki, sejarah, dan plot yang menegangkan. The Da Vinci Code adalah novel thriller yang telah menjadi bestseller internasional.' WHERE title = 'The Da Vinci Code';

UPDATE books SET description = 'Novel pertama yang memperkenalkan karakter ikonik Sherlock Holmes dan Dr. Watson. Mengisahkan tentang kasus pembunuhan misterius yang membawa Holmes dan Watson ke Amerika Serikat. Novel ini menampilkan deduksi logis Holmes yang brilian dan kemampuannya untuk memecahkan misteri yang paling rumit sekalipun. A Study in Scarlet adalah awal dari salah satu seri detektif paling terkenal dalam sejarah sastra.' WHERE title = 'Sherlock Holmes: A Study in Scarlet';

UPDATE books SET description = 'Sebuah novel misteri klasik yang mengisahkan tentang Hercule Poirot yang harus memecahkan kasus pembunuhan di kereta Orient Express. Ketika seorang penumpang ditemukan tewas di kompartemen terkunci, Poirot harus menginterogasi semua penumpang untuk menemukan pembunuhnya. Novel ini terkenal dengan plot twist yang mengejutkan dan solusi yang cerdik. Murder on the Orient Express adalah salah satu karya terbaik Agatha Christie.' WHERE title = 'Murder on the Orient Express';

-- Update descriptions for Horror books
UPDATE books SET description = 'Sebuah novel horor psikologis yang mengisahkan tentang Jack Torrance, seorang penulis yang menjadi penjaga hotel terpencil bersama keluarganya. Hotel Overlook ternyata dihuni oleh roh-roh jahat yang mulai mempengaruhi Jack dan mengancam keluarganya. Novel ini mengeksplorasi tema-tema tentang kegilaan, kekerasan dalam keluarga, dan kekuatan supernatural. The Shining adalah salah satu novel horor paling menakutkan yang pernah ditulis.' WHERE title = 'The Shining';

UPDATE books SET description = 'Novel vampir klasik yang memperkenalkan karakter Count Dracula yang ikonik. Mengisahkan tentang perjuangan sekelompok orang untuk menghentikan Dracula yang berencana untuk pindah dari Transylvania ke Inggris. Novel ini ditulis dalam format epistolary (surat-menyurat) dan menciptakan atmosfer yang menegangkan dan menakutkan. Dracula telah menjadi dasar untuk banyak adaptasi film dan telah mempengaruhi genre horor selama lebih dari satu abad.' WHERE title = 'Dracula';

UPDATE books SET description = 'Sebuah novel horor gotik yang mengisahkan tentang Victor Frankenstein, seorang ilmuwan yang menciptakan makhluk hidup dari bagian-bagian tubuh mayat. Ketika makhluknya hidup, Frankenstein menyadari kesalahan fatalnya dan harus menghadapi konsekuensi dari tindakannya. Novel ini mengeksplorasi tema-tema tentang tanggung jawab ilmiah, penolakan, dan konsekuensi dari bermain Tuhan. Frankenstein adalah salah satu novel horor paling berpengaruh dalam sejarah sastra.' WHERE title = 'Frankenstein';

-- Update descriptions for Science Fiction books
UPDATE books SET description = 'Sebuah novel fiksi ilmiah epik yang mengisahkan tentang Paul Atreides, putra seorang bangsawan yang dipaksa untuk melarikan diri ke gurun planet Arrakis. Di sana, dia harus belajar cara bertahan hidup dan akhirnya memimpin pemberontakan melawan Kaisar yang jahat. Novel ini mengeksplorasi tema-tema tentang politik, ekologi, agama, dan kekuasaan. Dune adalah salah satu novel fiksi ilmiah paling berpengaruh dan kompleks yang pernah ditulis.' WHERE title = 'Dune';

UPDATE books SET description = 'Sebuah novel fiksi ilmiah komedi yang mengisahkan tentang Arthur Dent, seorang manusia biasa yang terlibat dalam petualangan luar angkasa setelah Bumi dihancurkan untuk membangun jalan tol. Bersama dengan temannya Ford Prefect dan buku panduan berjudul The Hitchhiker\'s Guide to the Galaxy, Arthur menjelajahi alam semesta yang aneh dan lucu. Novel ini penuh dengan humor absurd, filosofi, dan komentar sosial yang cerdas.' WHERE title = 'The Hitchhiker\'s Guide to the Galaxy';

UPDATE books SET description = 'Sebuah novel fiksi ilmiah militer yang mengisahkan tentang Ender Wiggin, seorang anak laki-laki jenius yang direkrut untuk melatih di Battle School untuk mempersiapkan perang melawan alien Formics. Ender harus menghadapi tantangan fisik dan mental yang ekstrem sambil berjuang untuk memahami musuhnya. Novel ini mengeksplorasi tema-tema tentang perang, moralitas, dan konsekuensi dari keputusan yang sulit. Ender\'s Game adalah novel fiksi ilmiah yang powerful dan thought-provoking.' WHERE title = 'Ender\'s Game';

-- Update descriptions for History books
UPDATE books SET description = 'Sebuah buku sejarah yang menceritakan perjalanan Homo sapiens dari zaman batu hingga peradaban modern. Menggunakan pendekatan interdisipliner yang menggabungkan sejarah, biologi, dan antropologi, Harari menjelaskan bagaimana manusia berhasil mendominasi planet ini. Buku ini mengeksplorasi revolusi kognitif, revolusi pertanian, dan revolusi ilmiah yang membentuk peradaban manusia. Sapiens adalah buku yang mengubah cara kita memandang sejarah manusia.' WHERE title = 'Sapiens: A Brief History of Humankind';

UPDATE books SET description = 'Sebuah buku sejarah yang menjelaskan mengapa peradaban Eropa dan Asia berhasil mendominasi dunia, sementara peradaban lain tertinggal. Diamond menggunakan pendekatan geografis dan lingkungan untuk menjelaskan perbedaan perkembangan peradaban. Buku ini mengeksplorasi peran geografi, iklim, dan sumber daya alam dalam membentuk sejarah manusia. Guns, Germs, and Steel adalah karya sejarah yang revolusioner dan berpengaruh.' WHERE title = 'Guns, Germs, and Steel';

UPDATE books SET description = 'Sebuah risalah militer kuno yang ditulis oleh jenderal Tiongkok Sun Tzu. Buku ini berisi strategi dan taktik perang yang telah digunakan selama lebih dari 2000 tahun. Meskipun ditulis untuk konteks militer, prinsip-prinsipnya dapat diterapkan dalam berbagai aspek kehidupan modern, termasuk bisnis, politik, dan kehidupan pribadi. The Art of War adalah salah satu buku strategi paling berpengaruh dalam sejarah.' WHERE title = 'The Art of War';

-- Update descriptions for Science books
UPDATE books SET description = 'Sebuah buku tentang kosmologi dan fisika yang menjelaskan konsep-konsep kompleks tentang alam semesta dengan cara yang mudah dipahami. Hawking menjelaskan tentang Big Bang, lubang hitam, mekanika kuantum, dan teori relativitas Einstein. Buku ini ditulis untuk pembaca awam dan tidak memerlukan latar belakang sains yang mendalam. A Brief History of Time adalah salah satu buku sains populer paling terkenal dan berpengaruh.' WHERE title = 'A Brief History of Time';

UPDATE books SET description = 'Sebuah buku tentang alam semesta yang menggabungkan sains, sejarah, dan filosofi. Sagan menjelaskan tentang evolusi kosmos, dari Big Bang hingga kemunculan kehidupan di Bumi. Buku ini penuh dengan rasa kagum terhadap keindahan dan kompleksitas alam semesta. Cosmos adalah buku yang menginspirasi generasi pembaca untuk tertarik pada sains dan eksplorasi ruang angkasa.' WHERE title = 'Cosmos';

UPDATE books SET description = 'Sebuah buku tentang evolusi yang menjelaskan bagaimana gen adalah unit dasar seleksi alam. Dawkins menjelaskan konsep gen egois dan bagaimana gen mempengaruhi perilaku organisme untuk memastikan kelangsungan hidupnya. Buku ini menantang pemahaman tradisional tentang evolusi dan menawarkan perspektif baru tentang bagaimana kehidupan berevolusi. The Selfish Gene adalah salah satu buku sains paling berpengaruh abad ke-20.' WHERE title = 'The Selfish Gene';

-- Update descriptions for Self-Help books
UPDATE books SET description = 'Sebuah buku self-help yang mengajarkan tujuh kebiasaan yang dapat membantu seseorang menjadi lebih efektif dalam kehidupan pribadi dan profesional. Covey menjelaskan prinsip-prinsip seperti proaktif, mulai dengan akhir dalam pikiran, dan sinergi. Buku ini telah membantu jutaan orang di seluruh dunia untuk meningkatkan produktivitas dan mencapai tujuan mereka. The 7 Habits of Highly Effective People adalah buku self-help klasik yang timeless.' WHERE title = 'The 7 Habits of Highly Effective People';

UPDATE books SET description = 'Sebuah buku self-help klasik yang mengajarkan cara membangun hubungan yang baik dengan orang lain dan mempengaruhi mereka secara positif. Carnegie menjelaskan prinsip-prinsip seperti menunjukkan minat yang tulus pada orang lain, menjadi pendengar yang baik, dan membuat orang lain merasa penting. Buku ini telah membantu banyak orang untuk meningkatkan keterampilan interpersonal mereka. How to Win Friends and Influence People adalah buku self-help yang telah terjual jutaan kopi.' WHERE title = 'How to Win Friends and Influence People';

UPDATE books SET description = 'Sebuah buku tentang membangun kebiasaan baik dan menghilangkan kebiasaan buruk. Clear menjelaskan bagaimana kebiasaan bekerja dan memberikan strategi praktis untuk mengubah perilaku. Buku ini didasarkan pada penelitian ilmiah dan memberikan kerangka kerja yang jelas untuk perubahan yang berkelanjutan. Atomic Habits adalah buku self-help modern yang sangat praktis dan dapat diterapkan dalam kehidupan sehari-hari.' WHERE title = 'Atomic Habits';

-- Update descriptions for Business books
UPDATE books SET description = 'Sebuah buku tentang pendidikan keuangan yang mengajarkan perbedaan antara cara berpikir orang kaya dan orang miskin. Kiyosaki menjelaskan konsep aset dan liabilitas, serta pentingnya investasi dan membangun bisnis. Buku ini menantang pemikiran tradisional tentang uang dan menawarkan perspektif baru tentang kekayaan. Rich Dad Poor Dad adalah buku bisnis yang telah menginspirasi banyak orang untuk mengubah cara mereka memandang uang.' WHERE title = 'Rich Dad Poor Dad';

UPDATE books SET description = 'Sebuah buku tentang metodologi untuk membangun startup yang sukses. Ries menjelaskan konsep lean startup, termasuk build-measure-learn loop, minimum viable product (MVP), dan pivot. Buku ini memberikan kerangka kerja praktis untuk mengembangkan produk dan bisnis dengan cara yang efisien dan berbasis data. The Lean Startup adalah buku wajib bagi setiap entrepreneur modern.' WHERE title = 'The Lean Startup';

UPDATE books SET description = 'Sebuah buku tentang bagaimana perusahaan dapat beralih dari baik menjadi hebat. Collins menjelaskan karakteristik perusahaan hebat, termasuk kepemimpinan Level 5, budaya disiplin, dan teknologi yang tepat. Buku ini didasarkan pada penelitian selama 5 tahun terhadap perusahaan-perusahaan yang berhasil membuat transisi dari baik ke hebat. Good to Great adalah buku bisnis yang telah menjadi klasik.' WHERE title = 'Good to Great';

-- Update descriptions for Young Adult books
UPDATE books SET description = 'Sebuah novel distopia yang mengisahkan tentang Katniss Everdeen, seorang remaja yang menjadi peserta dalam Hunger Games, sebuah acara televisi di mana remaja harus bertarung sampai mati. Ketika adiknya terpilih, Katniss secara sukarela menggantikannya dan harus bertarung untuk bertahan hidup. Novel ini mengeksplorasi tema-tema tentang kekuasaan, media, dan perlawanan terhadap penindasan. The Hunger Games adalah novel young adult yang powerful dan menginspirasi.' WHERE title = 'The Hunger Games';

UPDATE books SET description = 'Sebuah novel yang mengisahkan tentang Hazel Grace Lancaster, seorang remaja penderita kanker yang bertemu dengan Augustus Waters di kelompok pendukung kanker. Bersama-sama, mereka menjalani perjalanan emosional yang penuh dengan cinta, kehilangan, dan makna hidup. Novel ini mengeksplorasi tema-tema tentang penyakit, kematian, dan cinta sejati. The Fault in Our Stars adalah novel yang mengharukan dan indah yang telah menyentuh hati jutaan pembaca.' WHERE title = 'The Fault in Our Stars';

UPDATE books SET description = 'Sebuah novel distopia yang mengisahkan tentang Beatrice Prior, seorang remaja yang hidup dalam masyarakat yang dibagi menjadi lima faksi berdasarkan kepribadian. Ketika dia harus memilih faksi, Beatrice memilih Divergent, yang berarti dia tidak cocok dengan sistem yang ada. Novel ini mengeksplorasi tema-tema tentang identitas, pilihan, dan perlawanan terhadap konformitas. Divergent adalah novel young adult yang penuh dengan aksi dan intrik.' WHERE title = 'Divergent';

-- Update descriptions for remaining books with more detailed descriptions
-- This will add more context to books with short descriptions
UPDATE books SET description = CONCAT(description, ' Novel ini menawarkan wawasan yang mendalam tentang karakter dan tema-tema yang kompleks. Dengan gaya penulisan yang memukau dan plot yang menegangkan, buku ini akan membawa pembaca pada perjalanan emosional yang tak terlupakan. Cocok untuk pembaca yang menyukai sastra berkualitas tinggi dan cerita yang penuh makna.') WHERE description IS NOT NULL AND LENGTH(description) < 100;

-- Additional updates for books that might have been missed
UPDATE books SET description = 'Sebuah novel yang mengisahkan tentang sekelompok anak laki-laki yang terdampar di pulau tak berpenghuni setelah kecelakaan pesawat. Tanpa pengawasan orang dewasa, mereka harus membangun peradaban mereka sendiri, tetapi ketakutan dan insting primitif mereka mulai mengambil alih. Novel ini mengeksplorasi tema-tema tentang kemanusiaan, kekerasan, dan hilangnya peradaban. Lord of the Flies adalah peringatan yang kuat tentang sifat manusia yang sebenarnya.' WHERE title = 'Lord of the Flies' AND (description IS NULL OR LENGTH(description) < 100);

UPDATE books SET description = 'Sebuah novel yang mengisahkan tentang seorang gadis muda yang hidup di Nazi Jerman dan menemukan kekuatan dalam membaca dan menulis. Meskipun hidup dalam ketakutan dan penindasan, dia menemukan cara untuk melawan melalui kekuatan kata-kata. Novel ini mengeksplorasi tema-tema tentang perang, kemanusiaan, dan kekuatan literasi. The Book Thief adalah novel yang mengharukan dan indah yang menceritakan kisah dari perspektif yang unik.' WHERE title = 'The Book Thief' AND (description IS NULL OR LENGTH(description) < 100);

UPDATE books SET description = 'Sebuah novel filosofis yang mengisahkan tentang Santiago, seorang gembala muda yang melakukan perjalanan dari Spanyol ke Mesir untuk mencari harta karun. Sepanjang perjalanannya, dia belajar tentang pentingnya mengikuti impian dan mendengarkan hati. Novel ini penuh dengan kebijaksanaan spiritual dan pesan tentang pencarian makna hidup. The Alchemist adalah novel yang menginspirasi dan telah mengubah hidup banyak pembaca di seluruh dunia.' WHERE title = 'The Alchemist' AND (description IS NULL OR LENGTH(description) < 100);

